glooptest.compat_module = {}
glooptest.debug("MESSAGE","Loading Compat Module Now!")

dofile(minetest.get_modpath("glooptest").."/compat_module/config.cfg")

if GLOOPORES_SUPPORT == true then
	minetest.register_alias("gloopores:mineral_alatro", "glooptest:mineral_alatro")
	minetest.register_alias("gloopores:alatro_lump", "glooptest:alatro_lump")
	minetest.register_alias("gloopores:alatro_ingot", "glooptest:alatro_ingot")
	minetest.register_alias("gloopores:alatro_block", "glooptest:alatroblock")
	minetest.register_alias("gloopores:pick_alatro", "glooptest:pick_alatro")
	minetest.register_alias("gloopores:axe_alatro", "glooptest:axe_alatro")
	minetest.register_alias("gloopores:shovel_alatro", "glooptest:shovel_alatro")
	minetest.register_alias("gloopores:sword_alatro", "glooptest:sword_alatro")
	minetest.register_alias("gloopores:mineral_arol", "glooptest:mineral_arol")
	minetest.register_alias("gloopores:arol_lump", "glooptest:arol_lump")
	minetest.register_alias("gloopores:arol_ingot", "glooptest:arol_ingot")
	minetest.register_alias("gloopores:pick_arol", "glooptest:pick_arol")
	minetest.register_alias("gloopores:axe_arol", "glooptest:axe_arol")
	minetest.register_alias("gloopores:shovel_arol", "glooptest:shovel_arol")
	minetest.register_alias("gloopores:sword_arol", "glooptest:sword_arol")
	minetest.register_alias("gloopores:mineral_akalin", "glooptest:mineral_akalin")
	minetest.register_alias("gloopores:akalin_lump", "glooptest:akalin_lump")
	minetest.register_alias("gloopores:akalin_ingot", "glooptest:akalin_ingot")
	minetest.register_alias("gloopores:akalin_block", "glooptest:akalinblock")
	minetest.register_alias("gloopores:mineral_talinite", "glooptest:mineral_talinite")
	minetest.register_alias("gloopores:talinite_lump", "glooptest:talinite_lump")
	minetest.register_alias("gloopores:talinite_ingot", "glooptest:talinite_ingot")
	minetest.register_alias("gloopores:talinite_block", "glooptest:taliniteblock")
	minetest.register_alias("gloopores:mineral_kalite", "glooptest:mineral_kalite")
	minetest.register_alias("gloopores:kalite_lump", "glooptest:kalite_lump")
	minetest.register_alias("gloopores:kalite_torch", "glooptest:kalite_torch")
	minetest.register_alias("gloopores:mineral_desert_coal", "glooptest:mineral_desert_coal")
	minetest.register_alias("gloopores:mineral_desert_iron", "glooptest:mineral_desert_iron")
end