local chars = {
	[32] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[33] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[34] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,true, false,false,},
		{true, false,true, false,false,},
		{true, false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[35] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{true, true, true, true, true, },
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{true, true, true, true, true, },
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[36] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,true, true, true, false,},
		{true, false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[37] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, false,false,},
		{true, false,true, false,false,},
		{true, true, false,false,true, },
		{false,false,true, true, false,},
		{false,true, false,true, true, },
		{true, false,false,true, false,},
		{false,false,false,true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[38] = {
		{false,true, true, false,false,},
		{true, false,false,false,false,},
		{false,true, true, false,true, },
		{true, false,false,true, false,},
		{false,true, true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[39] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[40] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
	},
	[41] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[42] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{true, true, false,true, true, },
		{false,false,true, false,false,},
		{false,true, false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[43] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, true, true, true, },
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[44] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[45] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[46] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[47] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,true, },
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[48] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[49] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{true, true, true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[50] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{false,false,false,true, false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[51] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{false,false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[52] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,true, false,},
		{false,false,true, true, false,},
		{false,true, false,true, false,},
		{true, false,false,true, false,},
		{true, true, true, true, true, },
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[53] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, true, true, false,false,},
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[54] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, true, false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[55] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{true, false,false,true, false,},
		{false,false,false,true, false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[56] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[57] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, true, false,},
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[58] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[59] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[60] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[61] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[62] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[63] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[64] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, true, true, },
		{false,true, false,false,false,},
		{true, false,false,true, true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{true, false,false,true, true, },
		{false,true, false,false,false,},
		{false,false,true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[65] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, true, false,},
		{false,false,true, false,true, },
		{false,true, false,false,true, },
		{false,true, true, true, true, },
		{false,true, false,false,true, },
		{true, true, false,false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[66] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[67] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[68] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[69] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, true, },
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,false,false,},
		{false,true, false,false,true, },
		{true, true, true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[70] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, true, },
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,true, false,},
		{false,true, false,false,false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[71] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,false,false,},
		{true, false,true, true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[72] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, true, true, true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, false,false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[73] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, true, },
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[74] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, true, true, },
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[75] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,true, false,},
		{false,true, true, false,false,},
		{false,true, false,true, false,},
		{false,true, false,false,true, },
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[76] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,true, },
		{true, true, true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[77] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,true, },
		{true, true, false,true, true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{true, false,false,false,true, },
		{true, true, false,true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[78] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,false,true, },
		{false,true, true, false,true, },
		{false,true, false,true, true, },
		{false,true, false,false,true, },
		{true, true, false,false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[79] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[80] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,false,false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[81] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[82] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,false,true, },
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[83] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, true, false,},
		{true, false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,false,true, false,},
		{true, false,false,true, false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[84] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, true, },
		{true, false,true, false,true, },
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[85] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,false,true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[86] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{true, false,false,false,true, },
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[87] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{true, false,false,false,true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[88] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,true, false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, false,true, false,},
		{true, true, false,true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[89] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{true, false,false,false,true, },
		{false,true, false,true, false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[90] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{true, false,false,true, false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{true, false,false,true, false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[91] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, true, false,false,false,},
		{false,false,false,false,false,},
	},
	[92] = {
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,false,true, false,},
		{false,false,false,true, false,},
		{false,false,false,false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[93] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, true, false,false,false,},
		{false,false,false,false,false,},
	},
	[94] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,true, false,},
		{true, false,false,false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[95] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, true, },
		{false,false,false,false,false,},
	},
	[96] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[97] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,false,true, false,},
		{false,true, true, true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[98] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[99] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,false,false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[100] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, true, false,},
		{false,false,false,true, false,},
		{false,true, true, true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[101] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, true, true, false,false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[102] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, true, false,},
		{false,true, false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[103] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,true, },
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, true, false,},
		{false,false,false,true, false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
	},
	[104] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[105] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[106] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
		{true, true, true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, false,false,false,},
		{false,false,false,false,false,},
	},
	[107] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,true, true, },
		{false,true, false,true, false,},
		{false,true, true, false,false,},
		{false,true, false,true, false,},
		{true, true, false,true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[108] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{false,false,true, false,false,},
		{true, true, true, true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[109] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, false,},
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[110] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{true, true, true, false,true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[111] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[112] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,true, true, false,},
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, true, true, false,},
		{false,true, false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
	},
	[113] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, false,true, },
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{true, false,false,true, false,},
		{false,true, true, true, false,},
		{false,false,false,true, false,},
		{false,false,true, true, true, },
		{false,false,false,false,false,},
	},
	[114] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,true, true, true, },
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[115] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, true, true, false,},
		{true, false,false,false,false,},
		{false,true, true, false,false,},
		{false,false,false,true, false,},
		{true, true, true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[116] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, true, true, true, false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,true, },
		{false,false,true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[117] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,false,true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[118] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,false,true, },
		{false,true, false,false,false,},
		{false,false,true, false,true, },
		{false,false,true, false,true, },
		{false,false,false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[119] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{true, false,true, false,true, },
		{false,true, false,true, false,},
		{false,true, false,true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[120] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,true, false,},
		{false,false,true, false,false,},
		{false,true, false,true, false,},
		{true, true, false,true, true, },
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[121] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, false,true, true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,true, false,false,true, },
		{false,false,true, true, false,},
		{false,false,true, false,false,},
		{true, true, false,false,false,},
		{false,false,false,false,false,},
	},
	[122] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, true, true, true, false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{true, false,false,true, false,},
		{true, true, true, true, false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
	[123] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,false,false,false,false,},
	},
	[124] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[125] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{true, false,false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,false,true, false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{false,true, false,false,false,},
		{true, false,false,false,false,},
		{false,false,false,false,false,},
	},
	[126] = {
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,true, false,true, false,},
		{true, false,true, false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
		{false,false,false,false,false,},
	},
}
return chars
