version: "3.6"

services:
 testserver:
  image: ${ENGINE_IMAGE:-ghcr.io/minetest/minetest:latest}
  command: ["--config", "/minetest.conf"]
  user: root
  volumes:
    - "./:/root/.minetest/games/dreambuilder_game/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"

volumes:
  world: {}