version: "3.6"

services:
 sut:
  image: lscr.io/linuxserver/minetest:${ENGINE_VERSION:-5.8.0}
  entrypoint: "minetestserver --config /minetest.conf --gameid dreambuilder_game"
  user: root
  volumes:
    - "./:/root/.minetest/games/dreambuilder_game/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}